name: yggdrasil
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.1.1
  hotreloader: ^3.0.1
  json_serializable: ^4.1.4
  lints: ^1.0.1
  shelf_router_generator: ^1.0.1
dependencies:
  hive: ^2.0.4
  json_annotation: ^4.1.0
  shelf: ^1.2.0
  shelf_router: ^1.1.1
  uuid: ^3.0.4
  path: ^1.8.0
  redis: ^2.0.0
  postgres: ^2.3.2
  logging: ^1.0.1
  mime: ^1.0.0
